//GET https://newsapi.org/v2/top-headlines?country=us&category=business&apiKey=0fc509c42cd640b29bc0681869f93666 HTTP/1.1

//http://localhost:5000/api/news

# POST http://localhost:3000/api/signup HTTP/1.1
# Content-Type: application/json

# {
#     "fullname": "Farhan",
#     "username": "admin",
#     "password": "admin",

# }